### ISSUE TITLE
CVC4 for Python3

### ISSUE THREAD

**Issue by umangm** [CVC4/CVC4#1517]
I wanted to install CVC4 for Python3.
I followed instructions from this [webpage](https://mytekmek.wordpress.com/2015/05/22/cvc4-python-api-on-mac/) .
The instructions work fine and I can indeed run the example Python script with python, but not with python3.

The following is the error reported on running ` python3 examples/SimpleVC.py`

```
Traceback (most recent call last):
  File "/usr/local/cvc4/share/pyshared/CVC4.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: dlopen(/usr/local/cvc4/share/pyshared/_CVC4.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /usr/local/cvc4/share/pyshared/_CVC4.so
  Expected in: flat namespace
 in /usr/local/cvc4/share/pyshared/_CVC4.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/SimpleVC.py", line 26, in <module>
    import CVC4
  File "/usr/local/cvc4/share/pyshared/CVC4.py", line 17, in <module>
    _CVC4 = swig_import_helper()
  File "/usr/local/cvc4/share/pyshared/CVC4.py", line 16, in swig_import_helper
    return importlib.import_module('_CVC4')
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/usr/local/cvc4/share/pyshared/_CVC4.so, 2): Symbol not found: _PyClass_Type
  Referenced from: /usr/local/cvc4/share/pyshared/_CVC4.so
  Expected in: flat namespace
 in /usr/local/cvc4/share/pyshared/_CVC4.so
```
Was the installation incorrect ?

**Comment by 4tXJ7f** [comment]
Thanks for reporting this. I will look into it in the coming days and update our [homebrew tap](https://github.com/CVC4/homebrew-cvc4) with Python support.

**Comment by 4tXJ7f** [comment]
Here's a workaround until I have time to make the process more seamless:

- Create a Python 3 virtual environment: `python3 -m venv <venv name>`
- Activate the virtual environment: `source <venv name>/bin/activate`
- Configure CVC4 with the virtual environment activated (same parameters as before)
- Compile and install CVC4
- Create the `_CVC4.so` symlink and set `PYTHONPATH`
- Make `examples/SimpleVC.py` compatible with Python 3 (add parentheses in the `print` statements) and execute it using `python examples/SimpleVC.py` (Note: Since the virtual environment is active, this will use Python 3)

The reason for the issues is that the bindings have to be compiled against the libraries of the correct Python version. Currently, the configure script uses `python-config` to get the compilation options to link against the Python libraries, which usually returns the Python 2.x config.

**Comment by umangm** [comment]
I get the same error when I installed when I tried the virtual env hack.

**Comment by 4tXJ7f** [comment]
Did you do a fresh build? Executing the `configure` does not necessarily remove old files, so it could be that it didn't recompile the files for the Python bindings. Try deleting the `builds` folder and then do the steps. Sorry for the inconvenience.

If you tried a build from scratch and it didn't work, what version of CVC4 are you compiling? I'll then try and reproduce the problem.
