### ISSUE TITLE
Memory leak with produce-unsat-assumptions (off)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4099]
Hi,
For this formula:
~~~~
(set-logic NIA)
(set-option :produce-unsat-assumptions false)
(declare-const v0 Bool)
(declare-const i0 Int)
(declare-const i3 Int)
(declare-const i4 Int)
(declare-const i5 Int)
(declare-const i6 Int)
(declare-const i7 Int)
(declare-const i8 Int)
(declare-const i9 Int)
(declare-const i12 Int)
(declare-const i15 Int)
(declare-const i16 Int)
(declare-const i17 Int)
(declare-const v1 Bool)
(declare-const v2 Bool)
(declare-const v3 Bool)
(push 1)
(assert (forall ((q0 Int) (q1 Bool)) (=> (or v1 v0 q1 (distinct v1 (<= 90 66) v3 v2 (<= 90 66) v1 (<= 90 66) v1 (<= 90 66))) (> q0 55))))
(declare-const v4 Bool)
(push 1)
(declare-const v5 Bool)
(declare-const v6 Bool)
(push 1)
(declare-const v7 Bool)
(declare-const i20 Int)
(declare-const v8 Bool)
(push 1)
(declare-const i21 Int)
(assert (forall ((q2 Bool) (q3 Int) (q4 Bool) (q5 Bool)) (=> (distinct i16 q3) (not v7))))
(declare-const i22 Int)
(declare-const v9 Bool)
(declare-const v10 Bool)
(assert (exists ((q6 Bool) (q7 Int) (q8 Bool) (q9 Bool)) (distinct v1 (<= 90 66) v3 v2 (<= 90 66) v1 (<= 90 66) v1 (<= 90 66))))
(declare-const v11 Bool)
(declare-const v12 Bool)
(assert (exists ((q10 Bool) (q11 Int)) (=> (and q10 q10 q10 q10 (or v1 v0 v6 (>= (- (- i0) i4) 676) v0) (= (- (- (- i0) i4) i17 830 i9 i8) i21) v6 (= i6 i6) (= i9 830)) (> q11 q11))))
(push 1)
(assert (forall ((q12 Bool) (q13 Bool)) (not (or (= i6 i6) q13 q13 q13 q13 q13 q12))))
(declare-const i23 Int)
(declare-const v13 Bool)
(declare-const i24 Int)
(pop 1)
(declare-const v14 Bool)
(declare-const i25 Int)
(declare-const v15 Bool)
(assert (forall ((q14 Bool) (q15 Bool)) (not (distinct (or v1 (distinct i7 (- (- i0) i4)) v4 (>= i3 55) (= (>= 44 38) v0 v3 (<= 90 66) v1 (distinct v1 (<= 90 66) v3 v2 (<= 90 66) v1 (<= 90 66) v1 (<= 90 66)) (>= 44 38) v2) v6 (= i6 i6)) q14 q15 v0 q14 q14 q15 (not (= (- (- (- i0) i4) i17 830 i9 i8) i21)) v9 v3))))
(declare-const v16 Bool)
(push 1)
(push 1)
(declare-const v17 Bool)
(assert (or (= i9 830) (= i9 830) (= i9 830)))
(assert (or (= i9 830) (= i9 830) (= i9 830)))
(assert (or (= i9 830) (= i9 830) (= i9 830)))
(assert (or (= i9 830) (= i9 830) (= i9 830)))
(assert (or (= i9 830) (= i9 830) (= i9 830)))
(assert (=> (or (= i9 830) (= i9 830) (= i9 830)) (or (= i9 830) (= i9 830) (= i9 830))))
(assert (or (or (= i9 830) (= i9 830) (= i9 830)) (or (= i9 830) (= i9 830) (= i9 830))))
(check-sat)
(assert (or (= i9 830) (= i9 830) (= i9 830)))
(check-sat)
~~~~

ASAN detects a memory leak
~~~~
==146607==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7f72f44e7532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7f72f13fd2c0 in CVC4::TSatProof<CVC4::Minisat::Solver>::finalizeProof(unsigned int) (/home/peisen/test/tofuzz/cvc-build/lib/libcvc4.so.6+0x203b2c0)
    #2 0x7f72f13e321c in CVC4::Minisat::Solver::addClause_(CVC4::Minisat::vec<CVC4::Minisat::Lit>&, bool, unsigned int&) /src/prop/minisat/core/Solver.cc:494
    #3 0x7f72f14276e1 in CVC4::Minisat::SimpSolver::addClause_(CVC4::Minisat::vec<CVC4::Minisat::Lit>&, bool, unsigned int&) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/simp/SimpSolver.cc:179
    #4 0x7f72f14234c9 in CVC4::Minisat::SimpSolver::addClause(CVC4::Minisat::vec<CVC4::Minisat::Lit> const&, bool, unsigned int&) /home/peisen/test/tofuzz/CVC4/src/./prop/minisat/simp/SimpSolver.h:187
    #5 0x7f72f1420a7d in CVC4::prop::MinisatSatSolver::addClause(std::vector<CVC4::prop::SatLiteral, std::allocator<CVC4::prop::SatLiteral> >&, bool) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/minisat
.cpp:156
~~~~
OS: Ubuntu 16.04
Commit: 442ab0cdd85

**Comment by 4tXJ7f** [comment]
This is a duplicate of https://github.com/CVC4/cvc4-projects/issues/65. When using ASAN, I would recommend building CVC4 without proofs for the time being. We are working on a new proof engine that will fix these issues.
