### ISSUE TITLE
check-unsat-cores memory leak

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4103]
Hi,
For the following formula
~~~~
(set-logic BV)
(set-option :check-unsat-cores true)
(assert false)
(check-sat)
(exit)
~~~~

ASAN detects a memory leak
~~~~
==69213==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fabb0950532 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99532)
    #1 0x7fabad8662c0 in CVC4::TSatProof<CVC4::Minisat::Solver>::finalizeProof(unsigned int) (/home/peisen/test/tofuzz/cvc-build/lib/libcvc4.so.6+0x203b2c0)
    #2 0x7fabad84c21c in CVC4::Minisat::Solver::addClause_(CVC4::Minisat::vec<CVC4::Minisat::Lit>&, bool, unsigned int&) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:494
    #3 0x7fabad8906e1 in CVC4::Minisat::SimpSolver::addClause_(CVC4::Minisat::vec<CVC4::Minisat::Lit>&, bool, unsigned int&) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/simp/SimpSolver.cc:179
    #4 0x7fabad88c4c9 in CVC4::Minisat::SimpSolver::addClause(CVC4::Minisat::vec<CVC4::Minisat::Lit> const&, bool, unsigned int&) /home/peisen/test/tofuzz/CVC4/src/./prop/minisat/simp/SimpSolver.h:187
    #5 0x7fabad889a7d in CVC4::prop::MinisatSatSolver::addClause(std::vector<CVC4::prop::SatLiteral, std::allocator<CVC4::prop::SatLiteral> >&, bool) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/minisat
.cpp:156
    #6 0x7fabad82baff in CVC4::prop::CnfStream::assertClause(CVC4::NodeTemplate<false>, std::vector<CVC4::prop::SatLiteral, std::allocator<CVC4::prop::SatLiteral> >&) /home/peisen/test/tofuzz/CVC4/src/pro
p/cnf_stream.cpp:87
    #7 0x7fabad82bf56 in CVC4::prop::CnfStream::assertClause(CVC4::NodeTemplate<false>, CVC4::prop::SatLiteral) /home/peisen/test/tofuzz/CVC4/src/prop/cnf_stream.cpp:103
    #8 0x7fabad837e21 in CVC4::prop::TseitinCnfStream::convertAndAssert(CVC4::NodeTemplate<false>, bool) /home/peisen/test/tofuzz/CVC4/src/prop/cnf_stream.cpp:763
    #9 0x7fabad837591 in CVC4::prop::TseitinCnfStream::convertAndAssert(CVC4::NodeTemplate<false>, bool, bool, CVC4::ProofRule, CVC4::NodeTemplate<false>) /home/peisen/test/tofuzz/CVC4/src/prop/cnf_stream
.cpp:713
    #10 0x7fabad89fe0c in CVC4::prop::PropEngine::assertFormula(CVC4::NodeTemplate<false>) /home/peisen/test/tofuzz/CVC4/src/prop/prop_engine.cpp:134
    #11 0x7fabad90b3fb in CVC4::smt::SmtEnginePrivate::processAssertions() /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:3563
    #12 0x7fabad904826 in CVC4::SmtEngine::check() /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:3046
    #13 0x7fabad90e95b in CVC4::SmtEngine::checkSatisfiability(std::vector<CVC4::Expr, std::allocator<CVC4::Expr> > const&, bool, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:3753
    #14 0x7fabad90dcdc in CVC4::SmtEngine::checkSatisfiability(CVC4::Expr const&, bool, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:3678
    #15 0x7fabad90d244 in CVC4::SmtEngine::checkSat(CVC4::Expr const&, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:3638
    #16 0x7fabad91be28 in CVC4::SmtEngine::checkUnsatCore() /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:4609
    #17 0x7fabad90f4ba in CVC4::SmtEngine::checkSatisfiability(std::vector<CVC4::Expr, std::allocator<CVC4::Expr> > const&, bool, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:3835
    #18 0x7fabad90dcdc in CVC4::SmtEngine::checkSatisfiability(CVC4::Expr const&, bool, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:3678
~~~~

OS: Ubuntu 16.04
Commit: 442ab0cdd85

**Comment by 4tXJ7f** [comment]
This is a duplicate of https://github.com/CVC4/cvc4-projects/issues/65. When using ASAN, I would recommend building CVC4 without proofs for the time being. We are working on a new proof engine that will fix these issues.
