### ISSUE TITLE
cvc4 (with ASAN) heap-buffer-overflow on malformed input

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#4453]
```
[788] % cvc4 small.smt2
(error "Parse Error: small.smt2:4.0: Unexpected token: '<<EOF>>'.")
[789] % cvc4san small.smt2
=================================================================
==6760==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60600000095c at pc 0x7f1dd73d0c6f bp 0x7ffd6980f350 sp 0x7ffd6980f340
READ of size 1 at 0x60600000095c thread T0
  #0 0x7f1dd73d0c6e in CVC4::parser::parseErrorHelper(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (/local/suz-local/software/CVC4san/build/src/parser/libcvc4parser.so.6+0xd6c6e)
  #1 0x7f1dd73d2170 in CVC4::parser::AntlrInput::parseError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) (/local/suz-local/software/CVC4san/build/src/parser/libcvc4parser.so.6+0xd8170)
  #2 0x7f1dd73d810a in CVC4::parser::AntlrInput::reportError(ANTLR3_BASE_RECOGNIZER_struct*) (/local/suz-local/software/CVC4san/build/src/parser/libcvc4parser.so.6+0xde10a)
  #3 0x7f1dd76f2b52 in parseCommand(Smt2Parser_Ctx_struct*) (/local/suz-local/software/CVC4san/build/src/parser/libcvc4parser.so.6+0x3f8b52)
  #4 0x7f1dd73ecba1 in CVC4::parser::Parser::nextCommand() (/local/suz-local/software/CVC4san/build/src/parser/libcvc4parser.so.6+0xf2ba1)
  #5 0x5650576edc96 in runCvc4(int, char**, CVC4::Options&) (/local/suz-local/software/CVC4san/build-05012020211855-8236d7f9/bin/cvc4+0x17c96)
  #6 0x5650576e43b0 in main (/local/suz-local/software/CVC4san/build-05012020211855-8236d7f9/bin/cvc4+0xe3b0)
  #7 0x7f1dd24b8b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
  #8 0x5650576e4b39 in _start (/local/suz-local/software/CVC4san/build-05012020211855-8236d7f9/bin/cvc4+0xeb39)
...
SUMMARY: AddressSanitizer: heap-buffer-overflow (/local/suz-local/software/CVC4san/build/src/parser/libcvc4parser.so.6+0xd6c6e) in CVC4::parser::parseErrorHelper(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
...
==6760==ABORTING
[790] % 
[790] % cat small.smt2
(set-logic QF_S)
(declare-fun s () String)
(assert (= s "")
[791] %
```

OS: Ubuntu 18.04
Commit: 8236d7f

**Comment by 4tXJ7f** [comment]
This is a duplicate of #4069. The issue happens when we try to construct the parser error. I have a partial fix for this but I need to find the cycles to finish it up.
