### ISSUE TITLE
Memory leak on NRA formula 

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4576]
Hi,
For the following formula:
~~~~
(set-logic NRA)
(declare-const r0 Real)
(assert (exists ((q36 Real) (q37 Bool) (q38 Bool) (q39 Bool) (q40 Real) (q41 Bool)) (= 0.0 0.0 (/ 437686.0 r0) 0.0 0.96101)))
(check-sat)
~~~~

CVC4 throws a leak:
~~~~
=================================================================
==129861==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f00dd6d6662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0x7f00bfb9a0e8 in CVC4::NodeBuilder<2u>::constructNV() /home/peisen/test/tofuzz/CVC4/src/./expr/node_builder.h:1016
    #2 0x7f00bfb948f8 in CVC4::NodeBuilder<2u>::constructNode() /home/peisen/test/tofuzz/CVC4/src/./expr/node_builder.h:864
    #3 0x7f00bfb9333e in CVC4::NodeManager::mkNode(CVC4::kind::Kind_t, CVC4::NodeTemplate<false>, CVC4::NodeTemplate<false>) /home/peisen/test/tofuzz/CVC4/src/./expr/node_manager.h:1274
    #4 0x7f00c2741b93 in CVC4::SkolemManager::mkSkolem(CVC4::NodeTemplate<true>, CVC4::NodeTemplate<true>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cx
x11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, CVC4::ProofGenerator*) /home/peisen/test/tofuzz/CVC4/src/expr/skolem_manager.cpp:52
    #5 0x7f00c0b6b0cd in CVC4::theory::arith::TheoryArithPrivate::eliminateOperators(CVC4::NodeTemplate<true>) /home/peisen/test/tofuzz/CVC4/src/theory/arith/theory_arith_private.cpp:1349
    #6 0x7f00c0bd7929 in CVC4::theory::arith::TheoryArithPrivate::expandDefinition(CVC4::NodeTemplate<true>) /home/peisen/test/tofuzz/CVC4/src/theory/arith/theory_arith_private.cpp:5221
    #7 0x7f00c0b2e829 in CVC4::theory::arith::TheoryArith::expandDefinition(CVC4::NodeTemplate<true>) /home/peisen/test/tofuzz/CVC4/src/theory/arith/theory_arith.cpp:80
    #8 0x7f00c054ad31 in CVC4::smt::ProcessAssertions::expandDefinitions(CVC4::NodeTemplate<false>, std::unordered_map<CVC4::NodeTemplate<true>, CVC4::NodeTemplate<true>, CVC4::NodeHashFunction, std::equa
l_to<CVC4::NodeTemplate<true> >, std::allocator<std::pair<CVC4::NodeTemplate<true> const, CVC4::NodeTemplate<true> > > >&, bool) /home/peisen/test/tofuzz/CVC4/src/smt/process_assertions.cpp:741
    #9 0x7f00c053c39a in CVC4::smt::ProcessAssertions::apply(CVC4::preprocessing::AssertionPipeline&) /home/peisen/test/tofuzz/CVC4/src/smt/process_assertions.cpp:141
    #10 0x7f00c059b5b1 in CVC4::smt::SmtEnginePrivate::processAssertions() /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:1438
    #11 0x7f00c0598ecb in CVC4::SmtEngine::check() /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:1353
    #12 0x7f00c05a089b in CVC4::SmtEngine::checkSatisfiability(std::vector<CVC4::Expr, std::allocator<CVC4::Expr> > const&, bool, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:1655
    #13 0x7f00c059f35a in CVC4::SmtEngine::checkSatisfiability(CVC4::Expr const&, bool, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:1579
    #14 0x7f00c059e04a in CVC4::SmtEngine::checkSat(CVC4::Expr const&, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:1540
    #15 0x7f00c04c032f in CVC4::CheckSatCommand::invoke(CVC4::SmtEngine*) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:386
    #16 0x7f00c04ba4c3 in CVC4::Command::invoke(CVC4::SmtEngine*, std::ostream&) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:174
    #17 0x440111 in CVC4::main::smtEngineInvoke(CVC4::SmtEngine*, CVC4::Command*, std::ostream*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:205
    #18 0x43d3bf in CVC4::main::CommandExecutor::doCommandSingleton(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:121
    #19 0x43c6a1 in CVC4::main::CommandExecutor::doCommand(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:98
    #20 0x4268a1 in runCvc4(int, char**, CVC4::Options&) /home/peisen/test/tofuzz/CVC4/src/main/driver_unified.cpp:446
~~~~

OS: Ubuntu 16.04
Commit: 6a61c1a7

**Comment by 4tXJ7f** [comment]
Thanks for the report, I've been able to reproduce the issue and will take a look.

**Comment by 4tXJ7f** [comment]
I have submitted a PR that fixes the issue. Thanks again for the report. A side note: This issue did not only affect the benchmark posted here but several of our regressions were affected as well, meaning that it would have made our nightly ASan build fail. For fuzzing purposes it would probably be best to use the commit of the most recent successful nightly build. I will see if we can get that published in a convenient location.
