### ISSUE TITLE
Memory leak on real formula (unsat-core)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4691]
~~~~
(set-option :check-unsat-cores true)
(declare-const v0 Bool)
(declare-const v1 Bool)
(declare-const v3 Bool)
(declare-const v4 Bool)
(declare-const r2 Real)
(declare-const r4 Real)
(declare-const r5 Real)
(declare-const r10 Real)
(declare-const v5 Bool)
(declare-const v6 Bool)
(declare-const v31 Bool)
(assert (! (or (distinct v0 (and v5 v3 v1) v0 v1 v0 (< 744274233.0 r10 r2)) (distinct v0 (and v5 v3 v1) v0 v1 v0 (< 744274233.0 r10 r2)) (or v6 v3 (not v0) (distinct v0 (and v5 v3 v1) v0 v1 v0 (< 744274233.0 r10 r2)) v31 (distinct v0 (and v5 v3 v1) v0 v1 v0 (< 744274233.0 r10 r2)) v1 (and v5 v3 v1) v6 v6) (distinct v0 (and v5 v3 v1) v0 v1 v0 (< 744274233.0 r10 r2)) (<= (/ r2 r4) r2 r5 0.95235) v4) :named IP_21))
~~~~
cvc4 2faf908e
~~~~
=================================================================
==155866==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f313bdae592 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99592)
    #1 0x7f311e090127 in CVC4::DefineFunctionCommand::clone() const /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:1298
    #2 0x7f311e14fdc1 in CVC4::SmtEngine::defineFunction(CVC4::Expr, std::vector<CVC4::Expr, std::allocator<CVC4::Expr> > const&, CVC4::Expr, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:121
3
    #3 0x7f311e08f48a in CVC4::DefineFunctionCommand::invoke(CVC4::SmtEngine*) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:1271
    #4 0x7f311e090708 in CVC4::DefineNamedFunctionCommand::invoke(CVC4::SmtEngine*) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:1322
    #5 0x7f311e0736a3 in CVC4::Command::invoke(CVC4::SmtEngine*, std::ostream&) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:181
    #6 0x43ff67 in CVC4::main::smtEngineInvoke(CVC4::SmtEngine*, CVC4::Command*, std::ostream*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:205
    #7 0x43d215 in CVC4::main::CommandExecutor::doCommandSingleton(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:121
    #8 0x43c4f7 in CVC4::main::CommandExecutor::doCommand(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:98
    #9 0x426871 in runCvc4(int, char**, CVC4::Options&) /home/peisen/test/tofuzz/CVC4/src/main/driver_unified.cpp:446
    #10 0x439315 in main /home/peisen/test/tofuzz/CVC4/src/main/main.cpp:55

~~~~

**Comment by 4tXJ7f** [comment]
As mentioned [previously](https://github.com/CVC4/CVC4/issues/4103#issuecomment-599342138), it is a known issue that CVC4 leaks memory with unsat cores/proofs.
