### ISSUE TITLE
heap-buffer-overflow at expr/node.h:1117 (uf-ss-totality)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4865]
~~~~
(set-logic UFC)
(set-option :uf-ss-totality true)
(declare-sort S0 0)
(declare-const S0-0 S0)
(assert (fmf.card S0-0 2))
(push 1)
(assert false)
(check-sat)
(pop 1)
(check-sat)
~~~~

CVC4 33b96c65
~~~~
unsat
=================================================================
==134289==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000005b18 at pc 0x7fdc4caeb806 bp 0x7ffd31d6ec80 sp 0x7ffd31d6ec70
READ of size 8 at 0x602000005b18 thread T0
    #0 0x7fdc4caeb805 in CVC4::NodeTemplate<true>::NodeTemplate(CVC4::NodeTemplate<true> const&) /home/peisen/test/tofuzz/CVC4/src/./expr/node.h:1117
    #1 0x7fdc4f6e9e82 in CVC4::theory::uf::CardinalityExtension::SortModel::getTotalityLemmaTerm(int, int) /home/peisen/test/tofuzz/CVC4/src/theory/uf/cardinality_extension.cpp:1133
    #2 0x7fdc4f6e9101 in CVC4::theory::uf::CardinalityExtension::SortModel::addTotalityAxiom(CVC4::NodeTemplate<true>, int, CVC4::theory::OutputChannel*) /home/peisen/test/tofuzz/CVC4/src/theory/uf/cardin
ality_extension.cpp:1114
    #3 0x7fdc4f6f0f0b in CVC4::theory::uf::CardinalityExtension::SortModel::getCardinalityLiteral(unsigned int) /home/peisen/test/tofuzz/CVC4/src/theory/uf/cardinality_extension.cpp:1304
    #4 0x7fdc4f6dd615 in CVC4::theory::uf::CardinalityExtension::SortModel::assertCardinality(CVC4::theory::OutputChannel*, int, bool) /home/peisen/test/tofuzz/CVC4/src/theory/uf/cardinality_extension.cpp
:842
    #5 0x7fdc4f6f6d2e in CVC4::theory::uf::CardinalityExtension::assertNode(CVC4::NodeTemplate<true>, bool) /home/peisen/test/tofuzz/CVC4/src/theory/uf/cardinality_extension.cpp:1517
    #6 0x7fdc4f84297c in CVC4::theory::uf::TheoryUF::check(CVC4::theory::Theory::Effort) /home/peisen/test/tofuzz/CVC4/src/theory/uf/theory_uf.cpp:140
    #7 0x7fdc4f5c777b in CVC4::TheoryEngine::check(CVC4::theory::Theory::Effort) /home/peisen/test/tofuzz/CVC4/src/theory/theory_engine.cpp:469
    #8 0x7fdc4d59de67 in CVC4::prop::TheoryProxy::theoryCheck(CVC4::theory::Theory::Effort) /home/peisen/test/tofuzz/CVC4/src/prop/theory_proxy.cpp:62
    #9 0x7fdc4d4d55b4 in CVC4::Minisat::Solver::theoryCheck(CVC4::theory::Theory::Effort) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1190
    #10 0x7fdc4d4d3479 in CVC4::Minisat::Solver::propagate(CVC4::Minisat::Solver::TheoryCheckType) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1104
    #11 0x7fdc4d4db5c8 in CVC4::Minisat::Solver::search(int) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1407
    #12 0x7fdc4d4e25eb in CVC4::Minisat::Solver::solve_() /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1627
    #13 0x7fdc4d563b2d in CVC4::Minisat::SimpSolver::solve_(bool, bool) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/simp/SimpSolver.cc:148
    #14 0x7fdc4d55af6d in CVC4::Minisat::SimpSolver::solve(bool, bool) /home/peisen/test/tofuzz/CVC4/src/./prop/minisat/simp/SimpSolver.h:201
    #15 0x7fdc4d5530d0 in CVC4::prop::MinisatSatSolver::solve() /home/peisen/test/tofuzz/CVC4/src/prop/minisat/minisat.cpp:185
    #16 0x7fdc4d58b5aa in CVC4::prop::PropEngine::checkSat() /home/peisen/test/tofuzz/CVC4/src/prop/prop_engine.cpp:198
    #17 0x7fdc4d6f180e in CVC4::SmtEngine::check() /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:946
    #18 0x7fdc4d6f664f in CVC4::SmtEngine::checkSatisfiability(std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&, bool, bool) /home/peisen/test/tofuzz/CVC4/src/smt/s
mt_engine.cpp:1141
    #19 0x7fdc4d6f5c46 in CVC4::SmtEngine::checkSatisfiability(CVC4::NodeTemplate<true> const&, bool, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:1102
    #20 0x7fdc4d6f4513 in CVC4::SmtEngine::checkSat(CVC4::Expr const&, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:1053
    #21 0x7fdc4d5cb805 in CVC4::CheckSatCommand::invoke(CVC4::SmtEngine*) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:392
    #22 0x7fdc4d5c5809 in CVC4::Command::invoke(CVC4::SmtEngine*, std::ostream&) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:180
    #23 0x436827 in CVC4::main::smtEngineInvoke(CVC4::SmtEngine*, CVC4::Command*, std::ostream*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:205
    #24 0x433ad5 in CVC4::main::CommandExecutor::doCommandSingleton(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:121
    #25 0x432db7 in CVC4::main::CommandExecutor::doCommand(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:98
    #26 0x42186b in CVC4::main::CommandExecutor::doCommand(std::unique_ptr<CVC4::Command, std::default_delete<CVC4::Command> >&) (/home/peisen/test/tofuzz/CVC4/build/bin/cvc4+0x42186b)
    #27 0x41c429 in runCvc4(int, char**, CVC4::Options&) /home/peisen/test/tofuzz/CVC4/src/main/driver_unified.cpp:441

~~~~

**Comment by nafur** [comment]
Note that this is unrelated to incrementality, and with `Debug` an assertion is triggered:
```
(set-logic UFC)
(set-option :uf-ss-totality true)
(declare-sort S 0)
(declare-const x S)
(assert (fmf.card x 2))
(check-sat)
```
yields
```
Fatal failure within CVC4::NodeTemplate<ref_count>::NodeTemplate(const CVC4::NodeTemplate<ref_count>&) [with bool ref_count = true] at /home/gereon/cvc4_prs/src/./expr/node.h:1117
Check failure

 e.d_nv != __null
Expecting a non-NULL expression value!
```
What actually happens is the following:
In `uf/cardinality_extension.cpp` the function `getTotalityLemmaTerm( int cardinality, int i )` is called with `i = 1` but `d_totalityTerms[0]` only holds a single element.

**Comment by ajreynol** [comment]
Thanks for the report.  Notice that the predicate `fmf.card` is an expert-only predicate, thus I'm marking as minor.  I will look into fixing.
