### ISSUE TITLE
NULL pointer dereference on verbosity command

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#5448]
Hi, for the following formula, CVC4 a71274b992
~~~~
(set-logic NIA)
(synth-inv InvF ((x1 Int)))
(check-synth)

$ /cvc4 x.sl  -vvv
Invoking: (set-option :incremental false)

Invoking: (set-logic NIA)

CVC4 suffered a segfault in DEBUG mode.
Offending address is 0xe0
Looks like a NULL pointer was dereferenced.
Invoking: Aborted
~~~~

**Comment by ajreynol** [comment]
Stack trace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004241a3 in CVC4::api::Grammar::resolve (this=0x0) at /space/ajreynol/cvc4-ajr/src/api/cvc4cpp.cpp:2878
2878	/space/ajreynol/cvc4-ajr/src/api/cvc4cpp.cpp: No such file or directory.
(gdb) bt
#0  0x00000000004241a3 in CVC4::api::Grammar::resolve (this=0x0) at /space/ajreynol/cvc4-ajr/src/api/cvc4cpp.cpp:2878
#1  0x00000000004d3f14 in CVC4::SynthFunCommand::toStream (this=0x254b4c0, out=..., toDepth=-1, dag=1, language=CVC4::language::output::LANG_SYGUS_V2)
    at /space/ajreynol/cvc4-ajr/src/smt/command.cpp:660
#2  0x00000000004d1111 in CVC4::operator<< (out=..., c=...) at /space/ajreynol/cvc4-ajr/src/smt/command.cpp:55
#3  0x000000000040c35f in CVC4::main::CommandExecutor::doCommand (this=0x2520f20, cmd=0x254b4c0) at /space/ajreynol/cvc4-ajr/src/main/command_executor.cpp:96
#4  0x0000000000407896 in CVC4::main::CommandExecutor::doCommand (this=0x2520f20, cmd=...) at /space/ajreynol/cvc4-ajr/src/./main/command_executor.h:76
#5  0x000000000040657f in runCvc4 (argc=3, argv=0x7fffffffdf28, opts=...) at /space/ajreynol/cvc4-ajr/src/main/driver_unified.cpp:448
#6  0x000000000040bc00 in main (argc=3, argv=0x7fffffffdf28) at /space/ajreynol/cvc4-ajr/src/main/main.cpp:54
(gdb) quit
A debugging session is active.

	Inferior 1 [process 15801] will be killed.
```
