### ISSUE TITLE
Segment fault at deps/poly/src/polyxx/variable.cpp:24, 39

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#5534]
Hi, for the following formula,
cvc4 d0c352ec048
~~~~
(set-logic QF_UFNRA)
(declare-fun r1 () Real)
(declare-fun r7 () Real)
(declare-fun ufrb5 (Real Real Real Real Real) Bool)
(assert (ufrb5 (* r1 174.0 r7 6003.73) 0.0 0.0 0.0 0.0))
(push 1)
(assert (< r7 0.0 r1 0.0 174.0))
(check-sat)
(pop 1)
(check-sat)
~~~~
~~~~
==18782==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f30eac34380 bp 0x00000043b7a0 sp 0x7ffe7919a9d8 T0)
    #0 0x7f30eac3437f  (/home/peisen/test/tofuzz/CVC4/deps/install/lib/libpolyxx.so.0+0x2937f)
    #1 0x7f30eac34400 in poly::operator<<(std::ostream&, poly::Variable const&) /home/peisen/test/tofuzz/CVC4/deps/poly/src/polyxx/variable.cpp:24
    #2 0x7f30ee973983 in CVC4::theory::arith::nl::VariableMapper::operator()(poly::Variable const&) /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/poly_conversion.cpp:62
    #3 0x7f30ee887a99 in CVC4::theory::arith::nl::cad::CDCAC::checkIntegrality(unsigned long, poly::Value const&) /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/cad/cdcac.cpp:447
    #4 0x7f30ee8865e4 in CVC4::theory::arith::nl::cad::CDCAC::getUnsatCover(unsigned long, bool) /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/cad/cdcac.cpp:374
    #5 0x7f30ee87bf74 in CVC4::theory::arith::nl::CadSolver::checkFull() /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/cad_solver.cpp:74
    #6 0x7f30ee9683cd in CVC4::theory::arith::nl::NonlinearExtension::runStrategy(CVC4::theory::Theory::Effort, std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&, st
d::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&, std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&) /home/peisen/test/tofuzz/C
VC4/src/theory/arith/nl/nonlinear_extension.cpp:618
    #7 0x7f30ee966506 in CVC4::theory::arith::nl::NonlinearExtension::modelBasedRefinement() /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/nonlinear_extension.cpp:453
    #8 0x7f30ee967af0 in CVC4::theory::arith::nl::NonlinearExtension::interceptModel(std::map<CVC4::NodeTemplate<true>, CVC4::NodeTemplate<true>, std::less<CVC4::NodeTemplate<true> >, std::allocator<std::
pair<CVC4::NodeTemplate<true> const, CVC4::NodeTemplate<true> > > >&) /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/nonlinear_extension.cpp:571
    #9 0x7f30eea3bbc9 in CVC4::theory::arith::TheoryArith::collectModelValues(CVC4::theory::TheoryModel*, std::set<CVC4::NodeTemplate<true>, std::less<CVC4::NodeTemplate<true> >, std::allocator<CVC4::Node
Template<true> > > const&) /home/peisen/test/tofuzz/CVC4/src/theory/arith/theory_arith.cpp:240
    #10 0x7f30eea3ba43 in CVC4::theory::arith::TheoryArith::collectModelInfo(CVC4::theory::TheoryModel*, std::set<CVC4::NodeTemplate<true>, std::less<CVC4::NodeTemplate<true> >, std::allocator<CVC4::NodeT
emplate<true> > > const&) /home/peisen/test/tofuzz/CVC4/src/theory/arith/theory_arith.cpp:226
    #11 0x7f30eef36518 in CVC4::theory::ModelManagerDistributed::prepareModel() /home/peisen/test/tofuzz/CVC4/src/theory/model_manager_distributed.cpp:86
    #12 0x7f30eef3185f in CVC4::theory::ModelManager::buildModel() /home/peisen/test/tofuzz/CVC4/src/theory/model_manager.cpp:90
    #13 0x7f30eed54df3 in CVC4::theory::CombinationCareGraph::buildModel() /home/peisen/test/tofuzz/CVC4/src/theory/combination_care_graph.cpp:96
    #14 0x7f30ef89b331 in CVC4::TheoryEngine::check(CVC4::theory::Theory::Effort) /home/peisen/test/tofuzz/CVC4/src/theory/theory_engine.cpp:556
    #15 0x7f30ee5d201c in CVC4::prop::TheoryProxy::theoryCheck(CVC4::theory::Theory::Effort) /home/peisen/test/tofuzz/CVC4/src/prop/theory_proxy.cpp:61
    #16 0x7f30ee54f44c in CVC4::Minisat::Solver::theoryCheck(CVC4::theory::Theory::Effort) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1247
    #17 0x7f30ee54e6aa in CVC4::Minisat::Solver::propagate(CVC4::Minisat::Solver::TheoryCheckType) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1132
    #18 0x7f30ee5514b4 in CVC4::Minisat::Solver::search(int) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1465
    #19 0x7f30ee552e87 in CVC4::Minisat::Solver::solve_() /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1695
    #20 0x7f30ee596926 in CVC4::Minisat::SimpSolver::solve_(bool, bool) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/simp/SimpSolver.cc:153
    #21 0x7f30ee592e06 in CVC4::Minisat::SimpSolver::solve(bool, bool) /home/peisen/test/tofuzz/CVC4/src/./prop/minisat/simp/SimpSolver.h:201
    #22 0x7f30ee590c1b in CVC4::prop::MinisatSatSolver::solve() /home/peisen/test/tofuzz/CVC4/src/prop/minisat/minisat.cpp:185
    #23 0x7f30ee5ae065 in CVC4::prop::PropEngine::checkSat() /home/peisen/test/tofuzz/CVC4/src/prop/prop_engine.cpp:199
    #24 0x7f30ee6ca7b7 in CVC4::smt::SmtSolver::checkSatisfiability(CVC4::smt::Assertions&, std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&, bool, bool) /home/peis
en/test/tofuzz/CVC4/src/smt/smt_solver.cpp:161
    #25 0x7f30ee6a167f in CVC4::SmtEngine::checkSatInternal(std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&, bool, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_
engine.cpp:965
    #26 0x7f30ee6a0b3a in CVC4::SmtEngine::checkSat(CVC4::NodeTemplate<true> const&, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:909
    #27 0x7f30ee6a08b4 in CVC4::SmtEngine::checkSat() /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:894
    #28 0x7f30ee14fd07 in CVC4::api::Solver::checkSat() const /home/peisen/test/tofuzz/CVC4/src/api/cvc4cpp.cpp:4644
    #29 0x7f30ee5ecf76 in CVC4::CheckSatCommand::invoke(CVC4::api::Solver*, CVC4::SymbolManager*) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:393
    #30 0x7f30ee5ea8c2 in CVC4::Command::invoke(CVC4::api::Solver*, CVC4::SymbolManager*, std::ostream&) /home/peisen/test/tofuzz/CVC4/src/smt/command.cpp:181
    #31 0x41f322 in CVC4::main::solverInvoke(CVC4::api::Solver*, CVC4::SymbolManager*, CVC4::Command*, std::ostream*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:219
    #32 0x41e51c in CVC4::main::CommandExecutor::doCommandSingleton(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:129
    #33 0x41e157 in CVC4::main::CommandExecutor::doCommand(CVC4::Command*) /home/peisen/test/tofuzz/CVC4/src/main/command_executor.cpp:105
    #34 0x4165ad in CVC4::main::CommandExecutor::doCommand(std::unique_ptr<CVC4::Command, std::default_delete<CVC4::Command> >&) /home/peisen/test/tofuzz/CVC4/src/./main/command_executor.h:74
    #35 0x414538 in runCvc4(int, char**, CVC4::Options&) /home/peisen/test/tofuzz/CVC4/src/main/driver_unified.cpp:448
~~~~

**Comment by rainoftime** [comment]
**deps/poly/src/polyxx/variable.cpp:39**
~~~~
(set-logic QF_UFNRA)
(declare-fun r0 () Real)
(declare-fun ufrb5 (Real Real Real Real Real) Bool)
(declare-fun r1 () Real)
(push 1)
(assert (> r1 0.0 r0))
(check-sat)
(pop 1)
(assert (ufrb5 0.0 (* r0 r1 r1 r1 r1) 0.0 0.0 0.0))
(check-sat)
~~~~
~~~~
sat
Fatal failure within CVC4::Node CVC4::theory::arith::nl::VariableMapper::operator()(const poly::Variable&) at /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/poly_conversion.cpp:61
Check failure

 it != mVarpolyCVC.end()
Expect variable ASAN:SIGSEGV
=================================================================
==21366==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fc9ce577380 bp 0x00000043b7a0 sp 0x7ffd55d6b0a8 T0)
    #0 0x7fc9ce57737f  (/home/peisen/test/tofuzz/CVC4/deps/install/lib/libpolyxx.so.0+0x2937f)
    #1 0x7fc9ce577400 in poly::operator<<(std::ostream&, poly::Variable const&) /home/peisen/test/tofuzz/CVC4/deps/poly/src/polyxx/variable.cpp:24
    #2 0x7fc9d22b6983 in CVC4::theory::arith::nl::VariableMapper::operator()(poly::Variable const&) /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/poly_conversion.cpp:62
    #3 0x7fc9d21caa99 in CVC4::theory::arith::nl::cad::CDCAC::checkIntegrality(unsigned long, poly::Value const&) /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/cad/cdcac.cpp:447
    #4 0x7fc9d21c95e4 in CVC4::theory::arith::nl::cad::CDCAC::getUnsatCover(unsigned long, bool) /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/cad/cdcac.cpp:374
    #5 0x7fc9d21bef74 in CVC4::theory::arith::nl::CadSolver::checkFull() /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/cad_solver.cpp:74
    #6 0x7fc9d22ab3cd in CVC4::theory::arith::nl::NonlinearExtension::runStrategy(CVC4::theory::Theory::Effort, std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&, st
d::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&, std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&) /home/peisen/test/tofuzz/C
VC4/src/theory/arith/nl/nonlinear_extension.cpp:618
    #7 0x7fc9d22a9506 in CVC4::theory::arith::nl::NonlinearExtension::modelBasedRefinement() /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/nonlinear_extension.cpp:453
    #8 0x7fc9d22aaaf0 in CVC4::theory::arith::nl::NonlinearExtension::interceptModel(std::map<CVC4::NodeTemplate<true>, CVC4::NodeTemplate<true>, std::less<CVC4::NodeTemplate<true> >, std::allocator<std::
pair<CVC4::NodeTemplate<true> const, CVC4::NodeTemplate<true> > > >&) /home/peisen/test/tofuzz/CVC4/src/theory/arith/nl/nonlinear_extension.cpp:571
    #9 0x7fc9d237ebc9 in CVC4::theory::arith::TheoryArith::collectModelValues(CVC4::theory::TheoryModel*, std::set<CVC4::NodeTemplate<true>, std::less<CVC4::NodeTemplate<true> >, std::allocator<CVC4::Node
Template<true> > > const&) /home/peisen/test/tofuzz/CVC4/src/theory/arith/theory_arith.cpp:240
    #10 0x7fc9d237ea43 in CVC4::theory::arith::TheoryArith::collectModelInfo(CVC4::theory::TheoryModel*, std::set<CVC4::NodeTemplate<true>, std::less<CVC4::NodeTemplate<true> >, std::allocator<CVC4::NodeT
emplate<true> > > const&) /home/peisen/test/tofuzz/CVC4/src/theory/arith/theory_arith.cpp:226
    #11 0x7fc9d2879518 in CVC4::theory::ModelManagerDistributed::prepareModel() /home/peisen/test/tofuzz/CVC4/src/theory/model_manager_distributed.cpp:86
    #12 0x7fc9d287485f in CVC4::theory::ModelManager::buildModel() /home/peisen/test/tofuzz/CVC4/src/theory/model_manager.cpp:90
    #13 0x7fc9d2697df3 in CVC4::theory::CombinationCareGraph::buildModel() /home/peisen/test/tofuzz/CVC4/src/theory/combination_care_graph.cpp:96
    #14 0x7fc9d31de331 in CVC4::TheoryEngine::check(CVC4::theory::Theory::Effort) /home/peisen/test/tofuzz/CVC4/src/theory/theory_engine.cpp:556
    #15 0x7fc9d1f1501c in CVC4::prop::TheoryProxy::theoryCheck(CVC4::theory::Theory::Effort) /home/peisen/test/tofuzz/CVC4/src/prop/theory_proxy.cpp:61
    #16 0x7fc9d1e9244c in CVC4::Minisat::Solver::theoryCheck(CVC4::theory::Theory::Effort) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1247
    #17 0x7fc9d1e916aa in CVC4::Minisat::Solver::propagate(CVC4::Minisat::Solver::TheoryCheckType) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1132
    #18 0x7fc9d1e944b4 in CVC4::Minisat::Solver::search(int) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1465
    #19 0x7fc9d1e95e87 in CVC4::Minisat::Solver::solve_() /home/peisen/test/tofuzz/CVC4/src/prop/minisat/core/Solver.cc:1695
    #20 0x7fc9d1ed9926 in CVC4::Minisat::SimpSolver::solve_(bool, bool) /home/peisen/test/tofuzz/CVC4/src/prop/minisat/simp/SimpSolver.cc:153
    #21 0x7fc9d1ed5e06 in CVC4::Minisat::SimpSolver::solve(bool, bool) /home/peisen/test/tofuzz/CVC4/src/./prop/minisat/simp/SimpSolver.h:201
    #22 0x7fc9d1ed3c1b in CVC4::prop::MinisatSatSolver::solve() /home/peisen/test/tofuzz/CVC4/src/prop/minisat/minisat.cpp:185
    #23 0x7fc9d1ef1065 in CVC4::prop::PropEngine::checkSat() /home/peisen/test/tofuzz/CVC4/src/prop/prop_engine.cpp:199
    #24 0x7fc9d200d7b7 in CVC4::smt::SmtSolver::checkSatisfiability(CVC4::smt::Assertions&, std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&, bool, bool) /home/peis
en/test/tofuzz/CVC4/src/smt/smt_solver.cpp:161
    #25 0x7fc9d1fe467f in CVC4::SmtEngine::checkSatInternal(std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&, bool, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_
engine.cpp:965
    #26 0x7fc9d1fe3b3a in CVC4::SmtEngine::checkSat(CVC4::NodeTemplate<true> const&, bool) /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:909
~~~~

**Comment by nafur** [comment]
So what actually happens is that the nonlinear solver is called with an empty set of assertions, and the CAD solver doesn't like that.
