### ISSUE TITLE
Overflow Error in mkBitVector of Python API

### ISSUE THREAD

**Issue by NicolaasWeideman** [CVC4/CVC4#6260]
**Describe the bug**
The Python statement `slv.mkBitVector(32, 2**31)` yields the following error:
```
Traceback (most recent call last):
  File "mwe.py", line 13, in <module>
    bv = slv.mkBitVector(32, 2**31)
  File "cvc4.pxi", line 742, in pycvc4.Solver.mkBitVector
OverflowError: value too large to convert to int
```

I attached a minimal example:
[example.zip](https://github.com/CVC4/CVC4/files/6244805/example.zip)

**Comment by NicolaasWeideman** [comment]
It appears the error is caused by casting the value of the bit vector to a signed integer (see [here](https://github.com/CVC4/CVC4/blob/afaf4413775ff7d6054a5893f1397ad908e0773c/src/api/python/cvc4.pxi#L742)).
Pull request #6261 should fix this.
